/// Generated by AssetsRefGenerator on 2021/10/23
class Res {
  static const String1 = "assets/1.jpg";
  static const String2 = "assets/2.jpg";
  static const String8_fOyVKHrV4 = "assets/8_fOyVKHrV4.jpg";
  static const String android_logo_PNG27 = "assets/android_logo_PNG27.png";
  static const String Buser = "assets/Buser.jpg";
  static const String camer = "assets/camer.jpg";
  static const String computer = "assets/computer.png";
  static const String Costomicons = "assets/icons/Costomicons.ttf";
  static const String cover = "assets/cover.jpg";
  static const String cpu_PNG42 = "assets/cpu_PNG42.png";
  static const String FPC = "assets/FPC.jpg";
  static const String kor = "assets/kor.jpg";
  static const String lcd = "assets/lcd.jpeg";
  static const String LCD = "assets/LCD.jpg";
  static const String LCD1 = "assets/LCD1.jpg";
  static const String mic = "assets/mic.jpg";
  static const String microUSB = "assets/microUSB.jpg";
  static const String noteboock = "assets/noteboock.png";
  static const String photocamera = "assets/photocamera.png";
  static const String recever = "assets/recever.jpg";
  static const String scrin = "assets/scrin.jpg";
  static const String smartphone = "assets/smartphone.png";
  static const String smartphone_PNG101502 = "assets/smartphone_PNG101502.png";
  static const String subPCB = "assets/subPCB.jpg";
  static const String tablet = "assets/tablet.png";
  static const String tachskrin = "assets/tachskrin.jpg";
  static const String tich = "assets/tich.jpg";
  static const String TV = "assets/TV.png";
}
